//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecializedProps.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterial
    {
        public int Id { get; set; }
        public string IdOrder { get; set; }
        public int IdMaterial { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
    }
}
